nnn plugins echo to stderr

diff --git a/tools/nnn/plugins/newfile b/tools/nnn/plugins/newfile
--- a/tools/nnn/plugins/newfile
+++ b/tools/nnn/plugins/newfile
@@ -3,7 +3,7 @@
 # Create a new file from a template. #
 # ---------------------------------- #
 
-echo '[NEWFILE] Create new file from template'
+echo '[NEWFILE] Create new file from template' >&2
 
 set templates_dir ~/.config/nnn/file_templates
 printf '%s\n' $templates_dir/* | string replace $templates_dir/ '' | gum choose --header 'Choose template' | read selected || return
@@ -12,5 +12,5 @@ gum input --placeholder $selected --header 'Type filename' | read filename || re
 if test -n "$filename"
     cp --interactive $templates_dir/$selected $filename
 else
-    echo '[NEWFILE] Empty filename: Abort'
+    echo '[NEWFILE] Empty filename: Abort' >&2
 end
