Normalize nnn plugins interaction

diff --git a/tools/nnn/archive b/tools/nnn/archive
--- a/tools/nnn/archive
+++ b/tools/nnn/archive
@@ -1,5 +1,8 @@
 #!/usr/bin/fish
 
+set bold (tput bold)
+set reset (tput sgr0)
+
 # Get selected files
 set selected_files
 if test -s ~/.config/nnn/.selection
@@ -10,19 +13,19 @@ else
     set selected_files $nnn
 end
 
-echo >&2
-echo "Will compress the following $(count $selected_files) item(s):" >&2
-echo >&2
-for index in (seq (count $selected_files))
-    echo "$index: $selected_files[$index]" >&2
+echo
+echo $bold"[ARCHIVE] Going to compress the following $(count $selected_files) item(s):"$reset
+echo
+for i in (seq (count $selected_files))
+    echo "  $i: $selected_files[$i]"
 end
+echo
 
 function get_choice
-    echo >&2
     echo 'Which format to compress to?' >&2
     echo >&2
-    for index in (seq (count $choices))
-        echo "  $index. $choices[$index]" >&2
+    for i in (seq (count $choices))
+        echo "  $i: $choices[$i]" >&2
     end
     echo >&2
     read --line --prompt-str 'Your choice: ' index_choice
@@ -41,16 +44,16 @@ if test (count $selected_files) -eq 1
         set extension (get_choice)
         switch $extension
             case .zst
-                echo "Generating $selection.zst" >&2
+                echo "Generating $selection.zst"
                 zstd $selection
             case .gz
-                echo "Generating $selection.gz" >&2
+                echo "Generating $selection.gz"
                 gzip --keep $selection
             case .zip
-                echo "Generating $selection.zip" >&2
+                echo "Generating $selection.zip"
                 zip $selection.zip $selection
             case '*'
-                echo 'Abort' >&2
+                echo 'Abort'
                 return 1
         end
     # Single directory
@@ -59,47 +62,47 @@ if test (count $selected_files) -eq 1
         set extension (get_choice)
         switch $extension
             case .tar.zst
-                echo "Generating $selection.tar.zst" >&2
+                echo "Generating $selection.tar.zst"
                 tar --zstd --create --file $selection.tar.zst $selection
             case .tgz
-                echo "Generating $selection.tgz" >&2
+                echo "Generating $selection.tgz"
                 tar --gzip --create --file $selection.tgz $selection
             case .tar
-                echo "Generating $selection.tar" >&2
+                echo "Generating $selection.tar"
                 tar --create --file $selection.tar $selection
             case .zip
-                echo "Generating $selection.zip" >&2
+                echo "Generating $selection.zip"
                 zip -r $selection.zip $selection
             case '*'
-                echo 'Abort' >&2
+                echo 'Abort'
                 return 1
         end
     end
 else
     # Multiple files / directories
     set choices .tar.zst .tgz .tar .zip
-    echo >&2
     read --line --prompt-str 'Filename without extension: ' output
     if test -z $output
-        echo 'Abort' >&2
+        echo 'Abort'
         return 1
     end
+    echo
     set extension (get_choice)
     switch $extension
         case .tar.zst
-            echo "Generating $output.tar.zst" >&2
+            echo "Generating $output.tar.zst"
             tar --zstd --create --file $output.tar.zst $selected_files
         case .tgz
-            echo "Generating $output.tgz" >&2
+            echo "Generating $output.tgz"
             tar --gzip --create --file $output.tgz $selected_files
         case .tar
-            echo "Generating $output.tar" >&2
+            echo "Generating $output.tar"
             tar --create --file $output.tar $selected_files
         case .zip
-            echo "Generating $output.zip" >&2
+            echo "Generating $output.zip"
             zip -r $output.zip $selected_files
         case '*'
-            echo 'Abort' >&2
+            echo 'Abort'
             return 1
     end
 end
